# Generated by Django 4.1.1 on 2023-02-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.CharField(choices=[('adhar_card', 'Adhar Card'), ('income_certificate', 'Income Certificate'), ('cast_certificate', 'Cast Certificate'), ('SSC_marksheet', 'SSC Marksheet'), ('leaving_certificate', 'Leaving Certificate'), ('PAN_card', 'PAN Card'), ('reservation_certificate', 'Reservation Certificate'), ('driving_licence', 'Driving Licence'), ('passport', 'Passport')], max_length=150),
        ),
    ]
