# Generated by Django 4.1.1 on 2023-02-10 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0002_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
