# Generated by Django 4.1.2 on 2022-10-11 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced')], default='Single', max_length=10)),
                ('income_class', models.CharField(choices=[('BPL', 'Less Than 50000'), ('lower', '50000-250000'), ('middle', '250000-700000'), ('upper', 'Greater Than 700000')], default='middle', max_length=10)),
                ('cast_class', models.CharField(choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('general', 'General')], default='general', max_length=10)),
                ('education_class', models.CharField(choices=[('primary', 'Primary education(till 8th class)'), ('secondary', 'Secondary education(till 10th class)'), ('senior_secondary', 'Senior Secondary education (till 12th class)'), ('undergraduate', ' Undergraduate education'), ('postgraduate', 'Postgraduate education')], default='secondary', max_length=20)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
